name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/github-pipelines
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-24.04

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install common dependencies
        run: npm install

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    needs: setup

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install Lint
        run: npm install --save-dev eslint prettier

      - name: Run Lint
        run: npm run lint

  node-tests:
    name: Run Tests
    runs-on: ubuntu-24.04
    needs: setup

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  build-deployment:
    name: Build Deployment Artifact
    runs-on: ubuntu-24.04
    needs: [ lint, node-tests ]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-artifact
          path: ./dist/

      - name: Placeholder for Deployment
        run: echo "This is a placeholder for the Build Deployment Artifact job."
