name: Test

on:
  # Trigger the pipeline on every push and pull request to the main branch
  push:
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-24.04

    steps:
      # Step to check out the repository code
      - name: Check out the repository
        uses: actions/checkout@v4

      # Step to set up Node.js version 16
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      # Step to install all project dependencies
      - name: Install common dependencies
        run: npm install

  # Job to run tests using the test script
  node-tests:
    name: Run Tests
    runs-on: ubuntu-24.04
    needs: setup

    steps:
      # Step to check out the repository code
      - name: Check out the repository
        uses: actions/checkout@v4

      # Step to run the test suite
      - name: Run tests
        run: npm run test
